### ISSUE TITLE
Sorting in position column broken

### ISSUE THREAD

**Issue by marikaris** [molgenis/vip-report-template#110]
**Describe the bug**
When sorting the data based on position, nothing happens

**To Reproduce**
1. Start the vip report in dev mode (it's also broken when you generate the template, but this is the easiest)
2. Click on the position column
3. The arrows change, implying that the data will be sorted, but the ordering stays the same

**Expected behavior**
Data should sort based on position.

**Screenshots**
I altered some of the chromosomes in the dummy data to illustrate the issue better, but it's just as broken with the original chromosomes (that data is however already sorted, so it doesn't look out of order, although you would still expect the order to be reversed once the position column is clicked)
<img width="197" alt="Screenshot 2021-01-21 at 10 33 46" src="https://user-images.githubusercontent.com/10075439/105332059-7b9ccc80-5bd4-11eb-84db-10df67287568.png">

<img width="205" alt="Screenshot 2021-01-21 at 10 33 55" src="https://user-images.githubusercontent.com/10075439/105332054-7a6b9f80-5bd4-11eb-9f9f-15aa697bb4ab.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome, firefox

**Comment by dennishendriksen** [comment]
Fixed in v3.0.0-beta: you cannot sort on position, but you can clear your sort which defaults to the vcf variant order which in practice corresponds to position sorting.
