### ISSUE TITLE
Report broken with merged VCF file 

### ISSUE THREAD

**Issue by marikaris** [molgenis/vip-report-template#130]
**Describe the bug**
When using a merged VCF file for which the AD field is present in some, but not all rows, the template breaks. 

**To Reproduce**
1. Generate a template using vip:
```
bash vip/pipeline.sh -i /your/input/file.vcf.gz -o ./test_bug.out.vcf -r /apps/data/1000G/phase1/human_g1k_v37_phiX.fasta -ann_vep "--refseq --exclude_predicted --use_given_ref" -k -f --args_preprocess "--filter_read_depth -1" --args_report "--max_records 1000"
```
2. Open test_bug.out.html in the browser
3. Uncheck `Only display records that match inheritance`
4. Check one of the other checkboxes or click on the magnifying glass icon of a structural variant

**Expected behavior**
Everything works

**Screenshots**
For the magnifying glass:
![Screenshot 2021-03-02 at 14 07 10](https://user-images.githubusercontent.com/10075439/109652927-a9c0e500-7b60-11eb-95cd-51b577e113b5.png)
For the checkboxes:
![Screenshot 2021-03-02 at 14 07 18](https://user-images.githubusercontent.com/10075439/109652947-af1e2f80-7b60-11eb-932f-f095cbdb63bc.png)

**Desktop (please complete the following information):**
 - OS: Created on gearshift, template opened in MacOS
 - Browser Chrome

**Comment by bartcharbon** [comment]
to reproduce the "AD" issue:
[test_snp_cnv.zip](https://github.com/molgenis/vip-report-template/files/6090322/test_snp_cnv.zip)

I think the checkbox issue is caused by the manually constructed test file, and is a result of a mismatch in headers and actual data.

**Comment by dennishendriksen** [comment]
File to reproduce the issue is invalid (missing CONTIG and CAP headers). Cannot reproduce when producing the report through vip v2.2.0 after fixing the input file manually.
