### ISSUE TITLE
Issues with variant details in genome browser

### ISSUE THREAD

**Issue by marikaris** [molgenis/vip-report-template#139]
**Describe the bug**
Two issues related to variant detail view in genome browser

**To Reproduce**
1. Start dev mode
2. Click on the first SNP in the table (click on position in column)
3. Click the patient SNP in the genome browser, scroll down to see the complete popup for the patient
![Screenshot 2021-04-22 at 11 23 20](https://user-images.githubusercontent.com/10075439/115690284-31ef8980-a35d-11eb-80bf-31303900b231.png)
4. Click on the dark blue reference SNP, scroll down to see the complete popup
See [object Object] on the bottom (ISSUE 1)
![Screenshot 2021-04-22 at 11 23 57](https://user-images.githubusercontent.com/10075439/115690350-429fff80-a35d-11eb-9795-46a2f18c833a.png)
5. Close the popup
6. Open the reference SNP popup again
The popup shows up way too low in the screen (ISSUE 2)
![Screenshot 2021-04-22 at 11 24 40](https://user-images.githubusercontent.com/10075439/115690453-5cd9dd80-a35d-11eb-9109-7c4fb4b58d22.png)

**Expected behavior**
I don't see object object and the variant details stay in the same location. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by dennishendriksen** [comment]
Cannot reproduce with https://github.com/molgenis/vip-report-template/pull/150

**Comment by marikaris** [comment]
Cannot reproduce
