### ISSUE TITLE
Error when not specifying reference in report-template

### ISSUE THREAD

**Issue by marikaris** [molgenis/vip-report-template#143]
**Describe the bug**
When you generate a template without specifying a reference in the `vip-report`, you get an error when clicking on the position column to get the gene track.

**To Reproduce**
Run the `vip-report` with:
`java -jar vcf-report.jar -t ~/git/vip-report-template/dist/vip-report-template.html -i trio.vcf.gz -pd trio.ped -o test-bug.html -g ncbiRefGene.txt.gz -f`
Open template
Click on position in position column to open genome browser
See error message:
`Uncaught (in promise) TypeError: Cannot convert undefined or null to object`

**Expected behavior**
No error and a genome browser

**Screenshots**

**Comment by dennishendriksen** [comment]
Issue still occurs in vip v2.2.0. A referene sequence is required in order to show the genome browser so the expected behavior would be to not create a hyperlink for the positions.
