### ISSUE TITLE
Error when specifying ped file

### ISSUE THREAD

**Issue by marikaris** [molgenis/vip-report-template#144]
**Describe the bug**
When specifying ped file for test data processed using vkgl (public) data, error when selecting `patient`

**To Reproduce**
Use: 
[public_consensus.vcf.gz](https://github.com/molgenis/vip-report-template/files/6404811/public_consensus.vcf.gz) (the vip pipeline output using vkgl public data). The regular trio ped file can be used:
```
FAM001	Patient	Father	Mother	1	2
FAM001	Father	0	0	1	2
FAM001	Mother	0	0	2	1

```
Run the `vip-report` with:
`java -jar vcf-report.jar -t ~/git/vip-report-template/dist/vip-report-template.html -i public_consensus.vcf.gz -o test-bug.html -g ncbiRefGene.txt.gz -r human_g1k_v37_phiX.fasta.gz -pd trio.ped -f`
Click on `Patient` to see the data of the "patient"
See error:
`TypeError: Cannot read property 'startsWith' of undefined`

**Expected behavior**
Patient info shows and no error.

**Comment by bartcharbon** [comment]
Seems to be related to missing genotypes for parents.

**Comment by dennishendriksen** [comment]
In vip v2.2.0 this issue still exists but results in a different error: https://github.com/molgenis/vip-report-template/issues/147. Closing this issue as duplicate.

**Comment by bartcharbon** [comment]
Issue manifests exactly as described in the issue in v2.2.0

**Comment by bartcharbon** [comment]
Fixed by: https://github.com/molgenis/vip-report-template/pull/149
