### ISSUE TITLE
TypeError: e.allele is undefined

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/vip-report-template#147]
Generate a report vcf-report v2.3.0 with a proband that has a father and/or mother with at least one variant having a call for the proband but no call for one or more alleles of father and/or mother. This results in error dialog `TypeError: e.allele is undefined` when opening the report. After closing the dialog a couple of times you can continue using the report, but no question marks are displayed for no-call father/mother alleles.

**Comment by bartcharbon** [comment]
Exact message of this bug is browser dependend, `e.allele is undefined` for firefox, 
`TypeError: Cannot read property 'startsWith' of undefined` for chrome and opera
