### ISSUE TITLE
SNP details in genome browser not entirely visible on smaller screens

### ISSUE THREAD

**Issue by marikaris** [molgenis/vip-report-template#154]
**Describe the bug**
When you open the SNP details in the genome browser on a small screen, the report will be partly out of the screen and you cannot see it. 

**To Reproduce**
1. Start in dev mode 
2. Move browser to small screen
3. Click on position of first variant to open genome browser
4. Click on the darkblue snp in the variants track of the genome browser:
![Screenshot 2021-06-18 at 15 20 58](https://user-images.githubusercontent.com/10075439/122567328-d6820500-d048-11eb-8a52-e82b2bfda4bd.png)
5. See that the pop up is cut off (see screenshot, that's over the entire width of the screen, you cannot scroll to see the rest)

**Expected behavior**
I see a small window with all information

**Screenshots**
<img width="1205" alt="Screenshot 2021-06-18 at 15 16 33" src="https://user-images.githubusercontent.com/10075439/122567028-8145f380-d048-11eb-83ea-1b951b4fc924.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by dennishendriksen** [comment]
Fixed in v3.0.0-beta:
![image](https://user-images.githubusercontent.com/2477186/173796816-537bf59e-a940-47da-95d0-adade6a6cfe2.png)
