### ISSUE TITLE
install fails because "igv-ui does not contain a package.json file."

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/vip-report-template#158]
**Describe the bug**
`npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/igv/igv-ui@git+https:/github.com/igvteam/igv-ui.git#v1.1.7" as it does not contain a package.json file.`

during npm install

**Comment by bartcharbon** [comment]
seems to be related to: https://github.com/npm/npm/issues/18266

Fixed by deleting package lock file, building and then reintroducing package lock file.

It seems te igv ui download is checked for a package json file while the code is still being downloaded.

**Comment by dennishendriksen** [comment]
Might be fixed in https://github.com/igvteam/igv.js/releases/tag/v2.9.4 where igv-ui is de dev dependency instead of a dependency.
