### ISSUE TITLE
Issues with decision tree fit to screen

### ISSUE THREAD

**Issue by marikaris** [molgenis/vip-report-template#165]
**Describe the bug**
When clicking on the "fit to screen" button in the decision tree, the tree should be completely scaled in the window, but only half of the tree is visible. 

**To Reproduce**
1. Go to the tree visualisation
2. Click on the fit to screen button
3. See that the tree is not scaled properly

**Expected behavior**
See the complete tree

**Additional context**
If the tree already fitting the screen, the behaviour is really weird as well. 
If you have the tree in horizontal view, the fit to screen does work.

![download](https://user-images.githubusercontent.com/10075439/130424870-91d9e846-6414-4336-8d99-77cb047c4f34.png)

**Comment by dennishendriksen** [comment]
Fixed in v3.0.0-beta
