### ISSUE TITLE
Licensing issue.

### ISSUE THREAD

**Issue by Sreelakshmikm22** [molgenis/vip-report-template#264]
Planning to use the library
licensed under GNU Lesser General Public License v3.0 only (LGPL-3.0)
we are not doing any modifications to the source code of the library
GPL, or our application can be made proprietary
can you please more insights into this

**Comment by dennishendriksen** [comment]
The LGPL v3.0 license is described in more detail [here](https://fossa.com/blog/open-source-software-licenses-101-lgpl-license/). Does this give the insights that you are looking for?

**Comment by Sreelakshmikm22** [comment]
As per the license term mentioned in link, my understanding is that there won’t be an issue with licensing of the proprietary product I am working on as I have not made any changes to the source code of the library and also, I would be adding the credits as mentioned in license documentation. If there’s any other action required to comply and use this library in proprietary product (commercial with its own license terms), please confirm.

**Comment by dennishendriksen** [comment]
There won’t be an issue indeed
